# Usa uma imagem base do Node.js
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de definição de pacotes
COPY package.json package-lock.json ./

# Instala as dependências do Node.js
RUN npm install

# Copia todo o resto do código do frontend
COPY . .