# Usa uma imagem base do Node.js
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /app

# Instala o Quasar CLI globalmente dentro do container
RUN npm install -g @quasar/cli

# Copia os arquivos de definição de pacotes
COPY package.json package-lock.json ./

# Instala as dependências, IGNORANDO scripts de post-install
RUN npm install --ignore-scripts

# Copia todo o resto do código do frontend
COPY . .

# O comando para iniciar (npm run dev) já está no seu docker-compose.yml